version: '3.7'

services:
  nginx_reverse_proxy:
    build: ./reverse_proxy_service
    ports:
      - '80:80'
      - "443:443"

    depends_on:
      - frontend
      - galcon_server

    volumes:
      - /etc/letsencrypt/archive/galcon-kpi.fun/:/etc/nginx/certs/

  frontend:
    build: ./frontend_service
    environment:
      - SERVER_URL=http://localhost

  galcon_server:
    build: .
    volumes:
      - ./src:/app/src
      - ./db:/app/db

    command: npm run start


